### ISSUE TITLE
i have some issue on lab9_final

### ISSUE THREAD

**Issue by devopsdymyr** [phcollignon/helm#2]
i have tried to create dev and test environment using lab9_final code 
my kubernetes cluster is in gcp and ingress nginx which is working fine with lab6 tested with frontend
current issue attached screenshot images
![Screenshot from 2019-10-30 20-23-21](https://user-images.githubusercontent.com/41105507/67869861-09b21080-fb54-11e9-95e4-7ceabb030552.png)
![Screenshot from 2019-10-30 20-25-03](https://user-images.githubusercontent.com/41105507/67869878-0fa7f180-fb54-11e9-932b-c7e24bfec5b8.png)
![Screenshot from 2019-10-30 20-26-07](https://user-images.githubusercontent.com/41105507/67869888-159dd280-fb54-11e9-8370-b0c89874425b.png)

**Comment by phcollignon** [comment]
Hi, I am using a hostpath Persistent Volume pointing to /mnt/data on the node and it seems you have no permissions to /mnt/data on your host. (https://github.com/phcollignon/helm/blob/master/lab9_helm_template_final/chart/guestbook/charts/database/templates/mongodb-persistent-volume.yaml)
Please create /mnt/data on the node or change the PV type to a Google Persistent Disk.
