### ISSUE TITLE
lab9 final 

### ISSUE THREAD

**Issue by devopsdymyr** [phcollignon/helm#4]
I have tested dev and Test which is deployed properly but not connecting to database.

![Screenshot from 2019-11-03 15-28-35](https://user-images.githubusercontent.com/41105507/68083448-a1fb0e80-fe4e-11e9-8867-a26ec2cc1a33.png)

![Screenshot from 2019-11-03 15-30-26](https://user-images.githubusercontent.com/41105507/68083481-ec7c8b00-fe4e-11e9-8ed1-140ad66c7acf.png)

**Comment by phcollignon** [comment]
Might be related to your other issue (https://github.com/phcollignon/helm/issues/2), the mongodb persistent volume is not accessible so the mongodb database does not start and the backend cannot connect to it.
